apiVersion: flipper.io.github.com/v1alpha1
kind: Flipper
metadata:
  labels:
    app.kubernetes.io/name: rollout-controller
    app.kubernetes.io/managed-by: kustomize
  name: flipper-sample
spec:
  interval: 3m
  match:
    labels:
      mesh: "true"
    namespace: "mesh"