/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen-v0.30. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/prembhaskal/rollout-controller/pkg/api/flipper/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeFlippers implements FlipperInterface
type FakeFlippers struct {
	Fake *FakeFlipperV1alpha1
	ns   string
}

var flippersResource = v1alpha1.SchemeGroupVersion.WithResource("flippers")

var flippersKind = v1alpha1.SchemeGroupVersion.WithKind("Flipper")

// Get takes name of the flipper, and returns the corresponding flipper object, and an error if there is any.
func (c *FakeFlippers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Flipper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(flippersResource, c.ns, name), &v1alpha1.Flipper{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Flipper), err
}

// List takes label and field selectors, and returns the list of Flippers that match those selectors.
func (c *FakeFlippers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.FlipperList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(flippersResource, flippersKind, c.ns, opts), &v1alpha1.FlipperList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.FlipperList{ListMeta: obj.(*v1alpha1.FlipperList).ListMeta}
	for _, item := range obj.(*v1alpha1.FlipperList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested flippers.
func (c *FakeFlippers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(flippersResource, c.ns, opts))

}

// Create takes the representation of a flipper and creates it.  Returns the server's representation of the flipper, and an error, if there is any.
func (c *FakeFlippers) Create(ctx context.Context, flipper *v1alpha1.Flipper, opts v1.CreateOptions) (result *v1alpha1.Flipper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(flippersResource, c.ns, flipper), &v1alpha1.Flipper{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Flipper), err
}

// Update takes the representation of a flipper and updates it. Returns the server's representation of the flipper, and an error, if there is any.
func (c *FakeFlippers) Update(ctx context.Context, flipper *v1alpha1.Flipper, opts v1.UpdateOptions) (result *v1alpha1.Flipper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(flippersResource, c.ns, flipper), &v1alpha1.Flipper{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Flipper), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeFlippers) UpdateStatus(ctx context.Context, flipper *v1alpha1.Flipper, opts v1.UpdateOptions) (*v1alpha1.Flipper, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(flippersResource, "status", c.ns, flipper), &v1alpha1.Flipper{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Flipper), err
}

// Delete takes name of the flipper and deletes it. Returns an error if one occurs.
func (c *FakeFlippers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(flippersResource, c.ns, name, opts), &v1alpha1.Flipper{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeFlippers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(flippersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.FlipperList{})
	return err
}

// Patch applies the patch and returns the patched flipper.
func (c *FakeFlippers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Flipper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(flippersResource, c.ns, name, pt, data, subresources...), &v1alpha1.Flipper{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Flipper), err
}
